# The chain ID of the StarkNet network that this node is connected to.
chain_id = "SN_MAIN"

# Connection with StarkNet feeder-gateway.
[central]
# Maximum number of concurrent requests to the feeder-gateway for getting data.
concurrent_requests = 10
# URL of the feeder-gateway to connect to.
url = "https://alpha-mainnet.starknet.io/"
# Retrying options in case of failed requests.
[central.retry]
# Base waiting time after a failed request, after which time increases exponentially.
base_millis = 30
# Maximum waiting time after a failed request.
max_delay_millis = 30000
# Maximum number of retries before giving up.
max_retries = 10

# JSON-RPC server configuration.
[gateway]
# IP:PORT address of the node's JSON-RPC server.
server_address = "0.0.0.0:8080"
# Maximum chunk size supported by the node in get_events requests.
max_events_chunk_size = 1000
# Maximum number of keys supported by the node in get_events requests.
max_events_keys = 100

# Monitoring server configuration.
[monitoring_gateway]
# IP:PORT address of the node's monitoring server.
server_address = "0.0.0.0:8081"

# Node's storage configuration.
[storage.db]
# Path of the node's storage directory. The storage file path will be <path>/<chain_id>.
# The path is not created automatically.
path = "./data"
# Maximum size of the node's storage.
max_size = 1099511627776 # 1TB.

# Synchronization configuration.
[sync]
# Time to wait before checking for a new block after the node is synchronized.
block_propagation_sleep_duration_secs = 10
# Waiting time before restarting synchronization after a recoverable error.
recoverable_error_sleep_duration_secs = 10
